import matplotlib.pyplot as plt

def waste_pie_chart(waste):

    fig,ax = plt.subplots()

    ax.pie(waste.values(),
           labels=waste.keys(),
           autopct='%1.1f%%')

    ax.set_title("Waste Composition")

    return fig


def energy_bar_chart(energy_results):

    fig,ax = plt.subplots()

    ax.bar(energy_results.keys(),
           energy_results.values())

    ax.set_ylabel("Energy (kWh)")
    ax.set_title("Energy Generated by Waste Type")

    return fig