import streamlit as st
import matplotlib.pyplot as plt
from calculations import energy_analysis
from config import TREATMENT_EFFICIENCY
from simulation import waste_growth_prediction

st.title("Smart Waste-to-Energy Dashboard")

# Check data
if "waste" not in st.session_state:
    st.warning("Please enter waste data on the Home page first.")
    st.stop()

waste = st.session_state.waste

energy_results, total_energy = energy_analysis(waste)

total_waste = sum(waste.values())

# KPI metrics
col1, col2 = st.columns(2)

col1.metric("Total Waste", f"{total_waste:.2f} kg")
col2.metric("Energy Generated", f"{total_energy:.2f} kWh")

st.divider()

# -------- Graph 1 Waste Composition --------

fig1, ax1 = plt.subplots()

ax1.pie(waste.values(),
        labels=waste.keys(),
        autopct='%1.1f%%')

ax1.set_title("Waste Composition")

# -------- Graph 2 Energy Generation --------

fig2, ax2 = plt.subplots()

ax2.bar(energy_results.keys(), energy_results.values())

ax2.set_title("Energy Generated by Waste Type")
ax2.set_ylabel("Energy (kWh)")

# -------- Graph 3 Treatment Comparison --------

methods = list(TREATMENT_EFFICIENCY.keys())
energies = [TREATMENT_EFFICIENCY[m] * total_waste for m in methods]

fig3, ax3 = plt.subplots()

ax3.bar(methods, energies)

ax3.set_title("Treatment Method Energy Efficiency")
ax3.set_ylabel("Energy Potential")

plt.xticks(rotation=25)

# -------- Graph 4 Waste Growth --------

years, growth = waste_growth_prediction(total_waste)

fig4, ax4 = plt.subplots()

ax4.plot(years, growth, marker="o")

ax4.set_title("Waste Growth Prediction")
ax4.set_xlabel("Years")
ax4.set_ylabel("Waste (kg)")

# -------- Layout --------

col1, col2 = st.columns(2)

with col1:
    st.pyplot(fig1)

with col2:
    st.pyplot(fig2)

col3, col4 = st.columns(2)

with col3:
    st.pyplot(fig3)

with col4:
    st.pyplot(fig4)